Fixes #3302 : Stop duplicating cacheHits and cacheMisses
This is a DaggyFix for https://github.com/ehcache/ehcache3/issues/3302
which seems to have been introduced by the preceding commit.

When CompensatingCounters had any cacheHits or cacheMisses,
snapshot() duplicated those numbers.  Thus, when
DefaultCacheStatistics.clear() was called more than once,
cacheHits and cacheMisses would more than double.
Then, because of normalize(), getCacheHits() and getCacheMisses()
returned 0, instead of negative numbers, until getHits() and
getMisses() more than doubled.

That issue is reproduced by adding a third call to innerClear() in
testClearingStats() in CacheCalculationTest and JCacheCalculationTest,
which then fail as follows, until this fix is applied.

     [Test worker] ERROR org.ehcache.integration.statistics.JCacheCalculationTest - Counters at time of assertion:  (H=0 M=0 P=3 R=2 Ev=0 Ex=0)
     org.assertj.core.api.SoftAssertionError:
     The following 2 assertions failed:
     1) [Hits] expected:<[1]L> but was:<[0]L>
     2) [Misses] expected:<[4]L> but was:<[0]L>

NB: when merging this with release branches, or the master branch,
manual merging may be necessary, because DefaultCacheStatistics was
moved around, most recently to org.ehcache.core.internal.statistics,
and copied to org.ehcache.management.statistics.  It looks like
both copies need this fix, although I don't see the same tests
for the latter.